#!/usr/bin/env python3
"""Jill — Personal AI Assistant CLI"""

import sys
import click
from config import load_config, ConfigError
from assistant import Assistant


@click.group()
@click.pass_context
def cli(ctx):
    """Jill — your personal AI assistant powered by Claude.

    Reads from Jira, Confluence, Obsidian, GitHub, and GitLab to answer
    questions, generate daily briefings, cross-reference topics, and produce
    TPM documents.
    """
    try:
        ctx.ensure_object(dict)
        ctx.obj["config"] = load_config()
        ctx.obj["assistant"] = Assistant(ctx.obj["config"])
    except ConfigError as e:
        click.echo(f"Configuration error: {e}", err=True)
        sys.exit(1)


@cli.command()
@click.argument("question")
@click.pass_context
def ask(ctx, question):
    """Ask a natural language question grounded in your data.

    Examples:

      jill ask "What are my open Jira tickets?"

      jill ask "What did I write about authentication in my notes?"
    """
    assistant: Assistant = ctx.obj["assistant"]
    click.echo(f"Asking: {question}\n")
    assistant.ask(question)


@cli.command()
@click.pass_context
def briefing(ctx):
    """Generate a daily summary of open tickets, recent Confluence updates, and relevant notes."""
    assistant: Assistant = ctx.obj["assistant"]
    click.echo("Generating daily briefing...\n")
    assistant.daily_briefing()


@cli.command()
@click.argument("topic")
@click.pass_context
def search(ctx, topic):
    """Cross-reference a topic across Jira, Confluence, Obsidian, GitHub, and GitLab.

    Examples:

      jill search "authentication"

      jill search "Q1 roadmap"
    """
    assistant: Assistant = ctx.obj["assistant"]
    click.echo(f"Searching across all sources for: {topic}\n")
    assistant.search(topic)


@cli.command()
@click.option("--unread", is_flag=True, default=False, help="Show unread emails only.")
@click.option("--search", "query", default="", metavar="QUERY", help="Search emails by keyword.")
@click.pass_context
def emails(ctx, unread, query):
    """Show recent Outlook emails, unread emails, or search your inbox.

    Examples:

      jill emails

      jill emails --unread

      jill emails --search "budget review"
    """
    assistant: Assistant = ctx.obj["assistant"]
    assistant.emails(unread_only=unread, search_query=query)


@cli.command("weekly-report")
@click.pass_context
def weekly_report(ctx):
    """Generate and save a weekly project status report to Obsidian.

    Fetches data from all configured sources for the past 7 days, asks
    Claude to generate a structured report, and saves it to your Obsidian
    vault under Weekly Reports/<YYYY-MM-DD>.md.
    """
    assistant: Assistant = ctx.obj["assistant"]
    assistant.weekly_report()


@cli.command("create")
@click.argument("type", metavar="TYPE")
@click.option("--project", default="", metavar="PROJ", help="Jira project key to scope context.")
@click.option("--topic", default="", metavar="TOPIC", help="Free-text topic for context.")
@click.pass_context
def create(ctx, type, project, topic):
    """Create a TPM document from a built-in template.

    TYPE must be one of: por | srd | roadmap | checklist

    The document is generated by Claude using context from your data sources
    and saved to Obsidian under Documents/<type>/.

    Examples:

      jill create por --project NVDRV

      jill create srd --topic "GPU memory management"

      jill create checklist --topic "RTX 5090 release"

      jill create roadmap
    """
    valid_types = ("por", "srd", "roadmap", "checklist")
    if type not in valid_types:
        click.echo(
            f"Error: invalid document type '{type}'. Must be one of: {', '.join(valid_types)}",
            err=True,
        )
        sys.exit(1)
    assistant: Assistant = ctx.obj["assistant"]
    assistant.create_document(doc_type=type, project=project, topic=topic)


@cli.command("plc-doc")
@click.option("--template", "template_ref", required=True, metavar="URL_OR_ID",
              help="Confluence page URL or ID to use as the PLC template.")
@click.option("--title", required=True, metavar="TITLE",
              help="Title for the new Confluence page.")
@click.option("--space", required=True, metavar="SPACE_KEY",
              help="Confluence space key for the new page (e.g. NVDRV).")
@click.option("--parent", "output_parent_id", default=None, metavar="PAGE_ID",
              help="Optional parent page ID to nest the new page under.")
@click.option("--jira-project", default=None, metavar="PROJECT_KEY",
              help="Jira project key to fetch open issues from.")
@click.option("--page", "confluence_page_refs", multiple=True, metavar="URL_OR_ID",
              help="Confluence page URL or ID to include as context. Repeatable.")
@click.option("--obsidian", "obsidian_search", multiple=True, metavar="TERM",
              help="Obsidian vault search term. Repeatable.")
@click.option("--meeting", "meeting_notes_refs", multiple=True, metavar="REF",
              help=(
                  "Meeting notes reference. Formats: "
                  "<confluence_url_or_id>, obsidian:<term>, text:<raw_text>. Repeatable."
              ))
@click.option("--context", "user_context", default=None, metavar="TEXT",
              help="Free-form context text to pass to Claude.")
@click.pass_context
def plc_doc(ctx, template_ref, title, space, output_parent_id, jira_project,
            confluence_page_refs, obsidian_search, meeting_notes_refs, user_context):
    """Create a populated PLC document from a Confluence template.

    Examples:

      jill plc-doc --template 123456789 --title "Blackwell GPU PLC" --space NVDRV

      jill plc-doc \\
        --template https://confluence.nvidia.com/pages/123456789 \\
        --title "RTX 5090 PLC Q2 2026" --space NVDRV --parent 987654321 \\
        --jira-project NVDRV \\
        --page https://confluence.nvidia.com/pages/111111 \\
        --obsidian "RTX 5090 roadmap" \\
        --meeting https://confluence.nvidia.com/pages/333333 \\
        --meeting "obsidian:Q2 sync notes" \\
        --meeting "text:Action: confirm yield numbers by March 1" \\
        --context "Target TDP is 600W, Ada Lovelace successor."
    """
    assistant: Assistant = ctx.obj["assistant"]
    assistant.create_plc_document(
        template_ref=template_ref,
        output_title=title,
        output_space=space,
        output_parent_id=output_parent_id,
        jira_project=jira_project,
        confluence_page_refs=list(confluence_page_refs),
        obsidian_search=list(obsidian_search),
        meeting_notes_refs=list(meeting_notes_refs),
        user_context=user_context,
    )


if __name__ == "__main__":
    cli()
